"""humanscape

Revision ID: df3b132a52a9
Revises: 81ed94f5fe8b
Create Date: 2021-11-17 00:40:23.345082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df3b132a52a9'
down_revision = '81ed94f5fe8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
